---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  log_level: info
  deprecations_as_errors: true
  chef_license: accept

platforms:
  - name: ubuntu-xenial
    driver_config:
      platform: ubuntu
      image: ubuntu:16.04
  - name: ubuntu-bionic
    driver_config:
      platform: ubuntu
      image: ubuntu:18.04
  - name: ubuntu-focal
    driver_config:
      platform: ubuntu
      image: ubuntu:20.04
  - name: ubuntu-jammy
    driver_config:
      platform: ubuntu
      image: ubuntu:22.04
  - name: ubuntu-kinetic
    driver_config:
      platform: ubuntu
      image: ubuntu:22.10
  - name: centos-centos7
    driver_config:
      platform: centos
      image: centos:centos7
  - name: centos-centos-stream8
    driver_config:
      platform: centos
      image: quay.io/centos/centos:stream8

suites:
  - name: 2x-chef16
    attributes:
      td_agent:
        version: 2.2.0
    driver_config:
      require_chef_omnibus: 16.8.14
    run_list:
      - recipe[smoke::default]
  - name: 2x-chef17
    attributes:
      td_agent:
        version: 2.2.0
    driver_config:
      require_chef_omnibus: 17.9.26
    run_list:
      - recipe[smoke::default]
  - name: 2x-chef18
    attributes:
      td_agent:
        version: 2.2.0
    driver_config:
      require_chef_omnibus: 18.1.29
    run_list:
      - recipe[smoke::default]
  - name: 3x-chef16
    attributes:
      td_agent:
        version: 3.1.0
    driver_config:
      require_chef_omnibus: 16.8.14
    run_list:
      - recipe[smoke::default]
  - name: 3x-chef17
    attributes:
      td_agent:
        version: 3.1.0
    driver_config:
      require_chef_omnibus: 17.9.26
    run_list:
      - recipe[smoke::default]
  - name: 3x-chef18
    attributes:
      td_agent:
        version: 3.1.0
    driver_config:
      require_chef_omnibus: 18.1.29
    run_list:
      - recipe[smoke::default]
